sudo: true
language: python

os:
  - linux

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

script:
  - chmod +x  ./configure-features.py
  - chmod +x  ./build-machine.py
  - chmod +x  ./build-all.py
  - ./configure-features.py -e WIFI -d BLUETOOTH -v
  - ./build-machine.py test_drive.h
  - ./configure-features.py -e BLUETOOTH -d WIFI -v
  - ./build-machine.py test_drive.h
  - ./configure-features.py -e BLUETOOTH WIFI -v
  - ./build-all.py

# notifications:
#   email:
#     on_success: change
#     on_failure: change
